<?php
/**
 * Copyright (c) 2008-2009
 * Computing for Volunteer Welfare Organizations (CVWO)
 * National University of Singapore
 *
 * Permission is hereby granted, free of charge, to any person obtainin
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject
 * to the following conditions:
 *
 * 1. The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * 2. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */
// $Id:
require_once drupal_get_path('module', 'cvwocodem2') . '/cvwocodem2_constants.php';
require_once drupal_get_path('module', 'cvwocodem2') . '/cvwocodem2_api.inc';
require_once drupal_get_path('module', 'cvwocodem2') . '/cvwocodem2_autocomplete.inc';
require_once drupal_get_path('module', 'cvwocodem2') . '/cvwocodem2_select.inc';
require_once drupal_get_path('module', 'cvwocodem2') . '/cvwocodem2_tag.inc';

/**
 * Register permission for mwshr module
*/
function cvwocodem2_permission() {
  return array(CVWOCODEM2_ADMIN_PERM => array(
    'title' => CVWOCODEM2_ADMIN_PERM));
}

/**
 * Standard Drupal Menu
 */
function cvwocodem2_menu() {

  $items = array();

  $items['admin/config/cvwo'] = array(
    'title'				 => 'CVWO',
    'description'		 => 'CVWO settings.',
    'position'			 => 'right',
    'weight'			 => -50,
    'page callback'		 => 'system_admin_menu_block_page',
    'access arguments'	 => array('access administration pages'),
    'file'				 => 'system.admin.inc',
    'file path'			 => drupal_get_path('module', 'system')
  );
  $items['admin/config/cvwo/cvwocodem2'] = array(
    'title' => t('Code Maintenance'),
    'description' => t('Modify Code Maintenance Options'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cvwocodem2_form'),
    'file'=>'cvwocodem2_form.inc',
    'access callback' => 'user_access', // access control
    'access arguments' => array(CVWOCODEM2_ADMIN_PERM)
  );

  $items[CVWOCODEM2_MODULE_AUTOCOMPLETE_PATH . '%'] = array(
    'type'				 => MENU_CALLBACK,
    'page callback'		 => 'cvwocodem2_autocomplete_callback',
    'page arguments'	 => array(2),
    'access callback'	 => true,
    'file'				 => 'cvwocodem2_autocomplete.inc'
  );

  return $items;

}

function cvwocodem2_element_info() {
  return array(
    'cvwocodem2_autocomplete' => array(
      '#input'			 => true,
      '#process'		 => array('cvwocodem2_autocomplete_element_process'),
      '#value_callback'	 => 'cvwocodem2_autocomplete_element_value_callback',
      '#theme_wrappers'	 => array('cvwocodem2_autocomplete', 'form_element')
    ),
    'cvwocodem2_select' => array(
      '#input'			 => true,
      '#process'		 => array('cvwocodem2_select_element_process'),
      '#value_callback'	 => 'cvwocodem2_select_element_value_callback',
      '#theme_wrappers'	 => array('cvwocodem2_select', 'form_element')
    ),
    'cvwocodem2_tag' => array(
      '#input'			 => true,
      '#process'		 => array('cvwocodem2_tag_element_process'),
      '#value_callback'	 => 'cvwocodem2_tag_element_value_callback',
      '#theme_wrappers'	 => array('cvwocodem2_tag', 'form_element')
    )
  );
}

function cvwocodem2_theme() {
  return array(
    'cvwocodem2_autocomplete'	 => array(
      'render element'	 => 'element',
      'files'			 => 'cvwocodem2_autocomplete.inc'
    ),
    'cvwocodem2_select'		 => array(
      'render element'	 => 'element',
      'files'			 => 'cvwocodem2_select.inc'
    ),
    'cvwocodem2_tag'		 => array(
      'render element'	 => 'element',
      'files'			 => 'cvwocodem2_tag.inc'
    )
  );
}
